### ISSUE TITLE
popup collision

### ISSUE THREAD

**Issue by TitDjeck** [ninja/ui#12]
Hi

you could use the jquery ui position utility to manage the collision of your popup.

simple to use, it will open your popup on top of the button if it is on the screen bottom.

**Comment by uipoet** [comment]
Ninja UI originally started with a dependency on some of the core jQuery UI interactions. We eventually built our own for simplicity and efficiency (those files are huge!)

PopUps are appended as the last dom object in the body and are absolutely positioned. They shouldn't collide with anything else. Would you please be more specific about what issue you've experienced?
