### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by uipoet** [ninja/ui#4]
Create process for generating/maintaining online API documentation. Embed this into ninjaui.com, ideally side by side with live examples.

**Comment by jarinudom** [comment]
Have you considered using something like Docco for this ( http://jashkenas.github.com/docco/ )?

**Comment by uipoet** [comment]
I have checked out Docco, thanks. Only problem there is lacking the ability to embed rendered examples. So far, https://github.com/visionmedia/dox is looking to be the best tool to start with.

**Comment by mheiduk** [comment]
We would like to use your UI on our website, but I am missing a documentation for it. Can you tell me when there will be someone? Best regards, Marc

**Comment by uipoet** [comment]
Marc, thank you for your interest! We are hard at work on documentation, targeting next weekend. In the meantime, check out this file for how the examples page was made: http://ninjaui.com/javascripts/examples.js

**Comment by Arnold42** [comment]
The popupList demo on the examples page is throwing a
"$popupList is not defined".

**Comment by uipoet** [comment]
Thank you for letting us know. We'll have it fixed by today's end.

**Comment by uipoet** [comment]
Fixed and deployed.
